export const POC_CASES = [
  ['blue knight with silver sword', 'walk'],
  ['small red fox', 'walk'],
  ['green goblin carrying a wooden club', 'attack'],
  ['purple wizard holding a staff', 'idle'],
  ['tiny yellow robot with square head', 'walk'],
  ['skeleton warrior carrying a shield', 'attack'],
  ['brown bear wearing a blue scarf', 'idle'],
  ['female ranger carrying a short bow', 'walk'],
  ['dark knight carrying a red sword', 'attack'],
  ['orange cat wearing a green cape', 'idle'],
  ['armored dwarf carrying a hammer', 'walk'],
  ['small turquoise slime creature', 'idle'],
  ['pirate carrying a curved sword', 'attack'],
  ['white rabbit in a red vest', 'walk'],
  ['purple mushroom warrior', 'attack'],
  ['small blue dragon with folded wings', 'idle'],
  ['astronaut with a gold visor', 'walk'],
  ['ninja wearing a dark blue outfit', 'attack'],
  ['farmer carrying a wooden pitchfork', 'idle'],
  ['brass clockwork soldier', 'walk'],
] as const;
